parameters:

services:
    file_upload.handler:
        class: NFC\UploadBundle\Services\FileHandler
        arguments: [@session, %nfc_upload.types%]

    file_upload.form.type:
        class: NFC\UploadBundle\Form\FileUploadType
        arguments: [@form.csrf_provider, @session]
        tags:
            - { name: form.type, alias: 'file_upload_type' }